# Generated by Django 3.2.5 on 2021-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
